In [1]:
# !pip install numpy

In [2]:
# In which directory 
import os
os.getcwd()

'C:\\Users\\Admin\\Desktop\\ChetanKate'

In [3]:
import numpy as np   # np is a alias name of numpy

In [4]:
# Numpy version display
np.__version__

'1.19.2'

# Create  a 1D Array

In [5]:
# 1D array means list of array
# array() inbuilt method of numpy

a=np.array([89.,76,34,90,43,90,20,76])   # "a" is numpy array object

In [6]:
a

array([89., 76., 34., 90., 43., 90., 20., 76.])

In [7]:
print(a)

[89. 76. 34. 90. 43. 90. 20. 76.]


In [8]:
# To check the dimension of array a, use inbuilt methods ndim of numpy
a.ndim

1

In [9]:
# To check the type of array.
a.dtype

dtype('float64')

In [10]:
# To check the datatype of a
type(a)

numpy.ndarray

In [11]:
# How many elements in numpy array a, use inbuilt method size.
a.size

8

In [12]:
# How many row and column in given numpy array a  use inbuilt method shape its return answer in tuple.
a.shape

(8,)

In [13]:
# Each element occupy 4 bytes memory space of array a
a.itemsize  # if int = 4bytes and float = 8 bytes.

8

In [14]:
# how many bytes are in store array a 
a.nbytes

64

In [15]:
# To find no of elements in numpy array
# 1. Size inbuilt method or 2. len() : inbuilt function
a.size

8

In [16]:
len(a)

8

In [17]:
# Create a 1d array with int type
a = np.array([45,67,89.76,54,67,20],int)
print(a)
print("Data type of a: ",a.dtype)

[45 67 89 54 67 20]
Data type of a:  int32


In [18]:
# There are 2 types of access data from 1d numpy array
# 1. Through Indexing    2. Through slicing

#1. Through Indexing
# Access 3rd elements (means 2nd index) from 1d numpy array a
a[2]

89

In [19]:
# Access multiple elements from 1d numpy array then
# first create a list of index.
# suppose access value at 1st and 4th index from 1d array
i = [1,4]  # Create the list of index.
a[i]       # a[[1,4]]


array([67, 67])

In [20]:
a[-2]      # access value at -2 index

67

In [21]:
#2. Access data from numpy 1d array through slicing.
#[start index : stop : index:step]

# Access data from 1st index to 4th index from numpy array a.
a[1:5:1]

array([67, 89, 54, 67])

In [22]:
# Access element from 3rd index till end
a[3:]

array([54, 67, 20])

In [23]:
a[-3:-1]

array([54, 67])

In [24]:
a[::-1]

array([20, 67, 54, 89, 67, 45])

In [25]:
# To show first 3 elements
a[:3]

array([45, 67, 89])

In [26]:
# To show last 3 elements
a[-3:]

array([54, 67, 20])

In [27]:
# To access element one by one from numpy arraya then use iteration means for loop
# for loop
for item in a:
    print(item)

45
67
89
54
67
20


In [28]:
# To find the sum of element in a
a.sum()

342

In [29]:
# To find the average of element in a
a.mean()

57.0

In [30]:
# To find the maximum element in a 
a.max()

89

In [31]:
# To create a 1D numpy array in another way : use arange()
x = np.arange(10,21,1)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [32]:
# Create 2D array means two dimensional numpy array
# 2D array means many row and in each row , many columns
# means create a matrix
# 2D array means list of list.

a=np.array([[60,35,66,74],[75,70,90,5],[78,49,35,88],[66,71,83,61]])
print("Matrix a : ")
print(a)

Matrix a : 
[[60 35 66 74]
 [75 70 90  5]
 [78 49 35 88]
 [66 71 83 61]]


In [33]:
# Access data from 2D numpy array
# 1 Indexing

# Accesss data from 2nd column of 1st row
a[1,2] # Matrixname[rowindex , colindex]

90

In [34]:
#Access all details (means all columns) of 2nd student means 1st index
a[1,]

array([75, 70, 90,  5])

In [35]:
# Access 1st and 2nd index col of 2nd and 3rd index rows.
a[2:4,1:3] # a row index start : row index stop, col index start : col index stop.

array([[49, 35],
       [71, 83]])

In [36]:
# Access last column of all rows
a[:,-1] ignore_index=True

array([74,  5, 88, 61])

In [37]:
# To find sum according to rows
a.sum(axis=1)   # axis = 1 use Left to right

array([235, 240, 250, 281])

In [38]:
# To find sum according to columns
a.sum(axis=0)  # axis = 0 use top to buttom.

array([279, 225, 274, 228])

In [39]:
# To find the maximum of columns 
a.max(axis=0)

array([78, 71, 90, 88])

In [40]:
# To find minimum of coumns
a.min(axis=0)

array([60, 35, 35,  5])

In [41]:
# To find the specific column maximun
z = a[:,0]
z.max()

78

In [42]:
# Create a zeros 1D array
Z=np.zeros(8) #by default type float
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
# Update the valuesat 2nd index with new values 90
Z[2] = 90
print(Z)

[ 0.  0. 90.  0.  0.  0.  0.  0.]


In [45]:
# Create a zeros 1D array
X=np.zeros(8,int) #by default type float
print(X)

[0 0 0 0 0 0 0 0]


In [46]:
# Create 2D zeros array
A = np.zeros((2,3))  # By default type will be float.
print(A) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [48]:
# Create 2D zeros array int type
B = np.zeros((2,3), int)  # By default type will be float.
print(B) 

[[0 0 0]
 [0 0 0]]


In [49]:
# Create 2D ones array int type
B = np.ones((2,3), int)  # By default type will be float.
print(B) 

[[1 1 1]
 [1 1 1]]


In [51]:
# Empty 2D array
C = np.empty((3,3))  # By default type will be float.
print(C) 

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.67187361e-321]
 [1.20480689e+132 1.03105893e-259 2.25563609e-153]]


In [57]:
# Identity matrix is always 2D
I = np.identity(2,int) # by default float
print(I)

[[1 0]
 [0 1]]


In [56]:
# or eye
I = np.eye(2,dtype=int)  #By default float
print(I)

[[1 0]
 [0 1]]


In [58]:
A = np.empty(5) # To fill 70 of all location.
A

array([4.94065646e-324, 4.94065646e-324, 0.00000000e+000, 0.00000000e+000,
       2.13616461e-306])

In [60]:
A.fill(70) # We have to create first empty matrix and then fill the matrix with values
A

array([70., 70., 70., 70., 70.])

In [63]:
# or
A=np.full(5,70) # It will create the matrix and also add the values in the matrix.
print(A)

[70 70 70 70 70]


In [65]:
# Braodcasting: 
# Vector is always 1D , it will be not the 2D vector.
A=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(A)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [66]:
# Create a vector means 1D array
B = np.array([5,6,7])
print(B)

[5 6 7]


In [67]:
# Addition
A+B

array([[15, 26, 37],
       [45, 56, 67],
       [75, 86, 97]])

In [68]:
# Multiplication:
A*B

array([[ 50, 120, 210],
       [200, 300, 420],
       [350, 480, 630]])